# Generated by Django 2.2.2 on 2019-06-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(help_text='간단한 설명문', max_length=100, verbose_name='DESCRIPTION'),
        ),
    ]
