# Generated by Django 2.2.2 on 2019-06-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityimage',
            name='rank',
            field=models.IntegerField(default=32),
        ),
    ]
