# Generated by Django 2.2.2 on 2019-07-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0002_cityimage_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityimage',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
