# Generated by Django 2.2.2 on 2019-07-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0003_cityimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityimage',
            name='choice',
            field=models.IntegerField(default=0),
        ),
    ]
