# Generated by Django 2.2.3 on 2019-07-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0004_cityimage_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('rank', models.IntegerField(default=32)),
                ('choice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Foodimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('rank', models.IntegerField(default=32)),
                ('choice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Moiveimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('rank', models.IntegerField(default=32)),
                ('choice', models.IntegerField(default=0)),
            ],
        ),
    ]
