# Generated by Django 2.2.3 on 2019-07-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0005_enterimage_foodimage_moiveimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moiveimage',
            new_name='Movieimage',
        ),
    ]
